#!/usr/bin/env python3
"""Generate simple conversation transcripts from Banking77 text/category pairs."""

from __future__ import annotations

import argparse
from pathlib import Path
import sys
import pandas as pd

TRANSCRIPT_TEMPLATE = "Customer: {text}\nAgent: [resolution generated by template]"


def require_demo_venv() -> None:
    expected = Path(__file__).resolve().parent.parent / ".venv"
    active = Path(sys.prefix).resolve()
    if active != expected.resolve():
        raise SystemExit(
            "ERROR: .venv is not active for this demo. "
            "Run: source scripts/00_setup_venv.sh"
        )


def main() -> None:
    require_demo_venv()

    parser = argparse.ArgumentParser()
    parser.add_argument("--input", required=True, help="Path to Banking77 CSV/TSV")
    parser.add_argument("--output", required=True, help="Path to generated conversation CSV")
    args = parser.parse_args()

    src = Path(args.input)
    dst = Path(args.output)
    dst.parent.mkdir(parents=True, exist_ok=True)

    if src.suffix.lower() == ".tsv":
        df = pd.read_csv(src, sep="\t")
    else:
        df = pd.read_csv(src)

    text_col = "text" if "text" in df.columns else df.columns[0]
    cat_col = "category" if "category" in df.columns else df.columns[1]

    out = pd.DataFrame(
        {
            "text": df[text_col].astype(str),
            "category": df[cat_col].astype(str),
            "transcript": df[text_col].astype(str).apply(
                lambda t: TRANSCRIPT_TEMPLATE.format(text=t)
            ),
        }
    )

    out.to_csv(dst, index=False)
    print(f"Generated {len(out)} rows at {dst}")
    print("Optional OCI GenAI hook: replace template with SDK call if PAYG is enabled.")


if __name__ == "__main__":
    main()
